services:
  zonefile-updater:
    build:
      context: zonefile-updater/_build
    restart: unless-stopped
    environment:
      - GIT_REPO_STORE=/zonefiles
      - GIT_REPO_URL=https://codeberg.org/litetex/rbldnsd-zone-asn.git
      - GIT_BRANCH=generated
      - UPDATE_INTERVAL=1h
    networks:
      # Use dedicated network that can do DNS resolution
      - zonefile-updater
    volumes:
      - ./_data/zonefiles:/zonefiles
    deploy:
      resources:
        limits:
          memory: 250M

  rbldnsd:
    build:
      context: rbldnsd/_build
    restart: unless-stopped
    depends_on:
      - zonefile-updater
    networks:
      asn-res:
        aliases:
          - v4.asnresolver.internal
          - v6.asnresolver.internal
    volumes:
      - ./_data/zonefiles:/zonefiles
    deploy:
      resources:
        limits:
          memory: 200M

  demo-dns-client:
    container_name: demo-dns-client
    build:
      context: demo-dns-client/_build
    networks:
      - asn-res

networks:
  zonefile-updater:
    enable_ipv6: true
  asn-res:
    name: "asn-res"
    enable_ipv6: true
