name: Updater

on:
  schedule:
    - cron: '34 3 * * *'
  workflow_dispatch:
    inputs:
      skip_download:
        type: boolean
        description: 'Skip download'
        default: false
      force_orphan_generated:
        type: boolean
        description: 'Force orphan generated branch'
        default: false

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v7
        with:
          pull: true
          load: true
          tags: zonefile-updater
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout cache branch
        uses: actions/checkout@v5
        continue-on-error: true # Branch may not exist
        with:
          repository: 'litetex/rbldnsd-zone-asn-cache'
          ref: 'cached'
          path: 'cached'
      
      - name: Checkout split cache branch
        uses: actions/checkout@v5
        continue-on-error: true # Branch may not exist
        with:
          repository: 'litetex/rbldnsd-zone-asn-cache'
          ref: 'cached-split'
          path: 'cached-split'

      - name: Run
        run: |
          set -e
          docker network create --ipv6 work || echo "Already exists"
          docker run --rm -v $PWD:/workdir \
            -w /workdir \
            --network work \
            --entrypoint /bin/bash \
            ${{ inputs.skip_download && '-e SKIP_DOWNLOAD=true' || '' }} \
            zonefile-updater /workdir/generate.sh
          docker network rm work || echo "Failed to remove"
      
      - name: Get Timestamp
        id: timestamp
        run:
          echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      - name: Save generated
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: generated
          publish_dir: ./out
          force_orphan: ${{ inputs.force_orphan_generated }}
          enable_jekyll: true # .nojekyll is not needed
          full_commit_message: ${{ steps.timestamp.outputs.timestamp }}

      - name: Save cache
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        continue-on-error: true # Just cache
        with:
          personal_token: ${{ secrets.CACHE_REPO_TOKEN }}
          publish_branch: cached
          publish_dir: ./cached
          force_orphan: true
          enable_jekyll: true # .nojekyll is not needed
          full_commit_message: ${{ steps.timestamp.outputs.timestamp }}
          external_repository: 'litetex/rbldnsd-zone-asn-cache'
          exclude_assets: 'latest-bview.gz' # Too big for repo

      - name: Save split cache
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        continue-on-error: true # Just cache
        with:
          personal_token: ${{ secrets.CACHE_REPO_TOKEN }}
          publish_branch: cached-split
          publish_dir: ./cached-split
          force_orphan: true
          enable_jekyll: true # .nojekyll is not needed
          full_commit_message: ${{ steps.timestamp.outputs.timestamp }}
          external_repository: 'litetex/rbldnsd-zone-asn-cache'

  mirror:
    runs-on: ubuntu-latest
    needs: update
    timeout-minutes: 5
    steps:
      - run: |
          git clone --bare https://github.com/litetex/rbldnsd-zone-asn.git
          cd rbldnsd-zone-asn.git
          echo "Starting push"
          git push --mirror https://litetex:${{ secrets.CB_TOKEN }}@codeberg.org/litetex/rbldnsd-zone-asn.git
          echo "Done"
